# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from .main_window import Ui_MainWindow
from data_base.hakaton_db import data_base


class MainWindow_super(Ui_MainWindow):
    def __init__(self):
        self.data = data_base('../data_base/main_db.db')

    def setupUi(self, MainWindow):
        Ui_MainWindow.setupUi(self, MainWindow)
        self.pushButton_new_coach.clicked.connect(self.add_coach)

    def retranslateUi(self, MainWindow):
        Ui_MainWindow.retranslateUi(self, MainWindow)
        print(self.data.return_coach_list())

    # def reboot_list(self):
    #     for i in

    def add_coach(self):
        self.data.add_coach(self.lineEdit_coach_name.text(), self.lineEdit_coach_price, self.lineEdit_coach_id)
        print(self.data.return_coach_list())
