# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from .main_window import Ui_MainWindow


class QMainWindow(Ui_MainWindow):
    def setupUi(self, MainWindow):
        Ui_MainWindow.setupUi(self, MainWindow)
        self.start_Button.clicked.connect(self.write_result)

    def write_result(self):
        text = [self.line_can_find.text()]
        text.extend(self.line_source.text().split(', '))
        work = work_ua.Work_ua(text)
        resumes = work.resumes(self.line_number.text())
        value_resumes = [str(i) for i in resumes[1]]
        jobs = work.jobs(self.line_number.text())
        value_jobs = [str(i) for i in jobs[1]]
        self.label_result_resume.setText('Результат: {}, кількість: {}'.format(resumes[0], len(value_resumes)))
        self.label_value_resume.setText('\n'.join(value_resumes))
        self.label_link_resume.setText('\n'.join(resumes[2]))

        self.label_result_job.setText('Результат: {}, кількість: {}'.format(jobs[0], len(value_jobs)))
        self.label_value_job.setText('\n'.join(value_jobs))
        self.label_link_job.setText('\n'.join(jobs[2]))
